name: Tests
on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v6
      id: go
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Tests
      run: make test
    
    - name: Upload to codecov
      uses: codecov/codecov-action@v7
